apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app
  namespace: exam-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: exam-pvc
        - name: cfg
          configMap:
            name: app-config
            items:
              - key: WELCOME_TEXT
                path: welcome.txt

      initContainers:
        - name: init-data
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /data/uploads
              cp /cfg/welcome.txt /data/welcome.txt
              chown -R 33:33 /data
              echo "[init] $(date) — welcome.txt + uploads/ pripravené"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: cfg
              mountPath: /cfg

      containers:
        - name: exam-app
          image: exam-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: data
              mountPath: /var/www/html/data
          # readinessProbe + livenessProbe (ak máš health.php a ready.php):
          # readinessProbe:
          #   httpGet:
          #     path: /ready.php
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /health.php
          #     port: 80
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
