apiVersion: v1
kind: Service
metadata:
  name: exam-be-svc          # ← týmto menom FE volá BE (DNS)
  namespace: exam-horvath
spec:
  type: ClusterIP            # interné — NEDOSTUPNÉ zvonku klastra
  selector:
    app: exam-be             # ← MUSÍ = labels v deployment-be.yaml
  ports:
    - port: 80               # exam-be-svc:80 v klastri
      targetPort: 80         # = containerPort BE
