apiVersion: v1
kind: Service
metadata:
  name: exam-fe-svc
  namespace: exam-meno
spec:
  type: NodePort             # verejné — dostupné z localhost
  selector:
    app: exam-fe             # ← MUSÍ = labels v deployment-fe.yaml
  ports:
    - port: 80
      targetPort: 80         # = containerPort FE (nginx počúva na 80)
      nodePort: 30080        # localhost:30080 (rozsah 30000-32767)
