apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: exam-horvath
data:
  APP_NAME: "Exam HorvathVK"
  LOG_LEVEL: "INFO"
  PROCESS_MODE: "prepend-marker"
  INPUT_DIR:  "/var/www/html/data/input"
  OUTPUT_DIR: "/var/www/html/data/output"

  SAMPLE_CSV_1: |
    name,age,city
    Alice,30,Bratislava
    Bob,25,Košice
    Cara,40,Žilina

  SAMPLE_CSV_2: |
    product,price,stock
    Pero,1.50,100
    Zošit,2.00,50
    Kniha,12.50,15
