apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam-pv
  # PV je cluster-scoped (NEMÁ namespace)
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/exam-meno"
