apiVersion: v1
kind: Service
metadata:
  name: exam-db-svc           # ← BE volá toto DNS meno (configmap-be.yaml: DB_HOST)
  namespace: exam-meno
spec:
  type: ClusterIP             # DB sa NIKDY nevystavuje zvonku
  selector:
    app: exam-db              # ← MUSÍ = labels v deployment-db.yaml
  ports:
    - port: 3306
      targetPort: 3306        # = containerPort MariaDB
