apiVersion: v1
kind: Service
metadata:
  name: exam-be-svc           # ← FE nginx volá toto DNS meno (proxy_pass)
  namespace: exam-horvath
spec:
  type: ClusterIP             # interné — neexistuje zvonku
  selector:
    app: exam-be              # ← MUSÍ = labels v deployment-be.yaml
  ports:
    - port: 80
      targetPort: 80
